import type { Metadata } from "next";
import "./globals.scss";
import { CSPostHogProvider } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CSPostHogProvider>
        <body>
          <main>{children}</main>
        </body>
      </CSPostHogProvider>
    </html>
  );
}
